name: Deploy React Portoflio to Github Pages

on: 
    workflow_dispatch:
    push:
        branches:
        - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Nodejs
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with: 
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./portfolio

      # Build project
      - name: Build the project
        run: npm run build
        working-directory: ./portfolio

      # Deploy to Github Pages
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./portfolio/dist
        